language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - wget https://github.com/redis/hiredis/archive/v0.13.3.tar.gz -O hiredis.tar.gz && mkdir -p hiredis && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 && cd hiredis && sudo make -j$(nproc) && sudo make install && sudo ldconfig && cd ..
  - pecl install -f swoole-2.0.12
before_script:
  - composer update --dev

script: composer test
